# This is for a generic Linux build
# For now, rtpip has to be built to run in 64 bit mode.

HOST_CPU = 
EXTRA_DEFINES =
DELIM = '
ARM32 = 0
LINUX = 1
MSYS2 = 0
MINGW = 0
CC = gcc
ECHO = /bin/echo -e
MAKE=make
RM=rm
MKDIR=mkdir
CFG =

include Makefile.common

